[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:opend]
command=/app/FutuOpenD/FutuOpenD
directory=/app/FutuOpenD
autostart=false
autorestart=true
stderr_logfile=/var/log/supervisor/opend.err.log
stdout_logfile=/var/log/supervisor/opend.out.log
user=root
environment=PYTHONPATH="/app/FutuOpenD" 